name: MacOS CI

on:
  push:
    branches:
      - master
      - dev
    tags:
      - v*

env:
  BUILD_TYPE: Release
  GNU_CC: /usr/local/bin/gcc-9
  GNU_CXX: /usr/local/bin/g++-9
  LLVM_CC: /usr/local/opt/llvm/bin/clang
  LLVM_CXX: /usr/local/opt/llvm/bin/clang++

jobs:
  macos:
    runs-on: macos-latest
    
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Install GNU C/C++ Compiler
      if: ${{ matrix.compiler == 'gcc' }}
      run: |
        brew install gcc@9
        export GNU_CC=gcc-9
        export GNU_CXX=g++-9

    - name: Install LLVM Clang
      if: ${{ matrix.compiler == 'clang' }}
      run: |
        brew install llvm
        export LLVM_CC=clang-10
        export LLVM_CXX=clang++-10

    - name: Install Eigen3
      run: |
        brew install eigen

    - name: CMake Build
      env:
        C_COMPILER: ${{ matrix.compiler }}
      run: |
        cmake -E make_directory ${{runner.workspace}}/build
        cd ${{runner.workspace}}/build
        if [ "$C_COMPILER" = "gcc" ]; then
          cmake $GITHUB_WORKSPACE \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DCMAKE_C_COMPILER=$GNU_CC \
            -DCMAKE_CXX_COMPILER=$GNU_CXX \
            -DEIGEN3_DIR=/usr/local/include/eigen3
        fi
        if [ "$C_COMPILER" = "clang" ]; then
          cmake $GITHUB_WORKSPACE \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DCMAKE_C_COMPILER=$LLVM_CC \
            -DCMAKE_CXX_COMPILER=$LLVM_CXX \
            -DEIGEN3_DIR=/usr/local/include/eigen3
        fi
        cmake --build . --config $BUILD_TYPE --parallel 2